### ISSUE TITLE
Not Able to Download the Dataset

### ISSUE THREAD

**Issue by Manasa-N-2504** [pythonlessons/mltu#14]

**Comment by pythonlessons** [comment]
error is know, link to download dataset doesn't work. Need to find a new link

**Comment by Manasa-N-2504** [comment]
Sir if possible can you provide the new link sir

**Comment by Charlieletscode** [comment]
https://fki.tic.heia-fr.ch/databases/download-the-iam-handwriting-database
This might be it

**Comment by Shrishti120** [comment]
The formate of this dataset is different from the one which is used in the tutorial.

**Comment by amoungui** [comment]
Hi, I have tis issue : 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 334.15it/s]
Traceback (most recent call last):
  File "C:\Users\Amoungui\Documents\Projets\AI System\mltu\Tutorials\03_handwriting_recognition\train.py", line 41, in <module>
    download_and_unzip("https://fki.tic.heia-fr.ch/databases/download-the-iam-handwriting-database", extract_to="Datasets")
  File "C:\Users\Amoungui\Documents\Projets\AI System\mltu\Tutorials\03_handwriting_recognition\train.py", line 36, in download_and_unzip
    zipfile = ZipFile(BytesIO(data))
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\zipfile.py", line 1312, in __init__
    self._RealGetContents()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\zipfile.py", line 1379, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file. I used this url : https://fki.tic.heia-fr.ch/databases/download-the-iam-handwriting-database. But I have the same error with the preview datasets link
